# Generated by Django 4.2.20 on 2025-04-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=280, verbose_name='Contenido')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published')], default='pending', max_length=10, verbose_name='State')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled date and time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date of publication')),
                ('tweet_id', models.CharField(blank=True, default='', max_length=50, verbose_name='Tweet ID')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Last error')),
            ],
            options={
                'verbose_name': 'Tweet',
                'verbose_name_plural': 'Tweets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TwitterCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key')),
                ('api_secret_key', models.CharField(max_length=255, verbose_name='API Secret Key')),
                ('access_token', models.CharField(max_length=255, verbose_name='Access Token')),
                ('access_token_secret', models.CharField(max_length=255, verbose_name='Access Token Secret')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Twitter Credentials',
                'verbose_name_plural': 'Twitter Credentials',
            },
        ),
    ]
