# Generated by Django 4.2.20 on 2025-05-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_note_delete_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('published_x', 'Published in X'), ('published_n', 'Published in Nostr'), ('published', 'Published')], default='pending', max_length=12, verbose_name='State'),
        ),
    ]
