# Generated by Django 4.2.20 on 2025-05-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_note_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nostrcredentials',
            name='relay_urls',
            field=models.TextField(blank=True, default='', help_text='Enter one relay URL per line', verbose_name='Relay URLs'),
        ),
    ]
